export const PRODUCT_LOAD_START = 'PRODUCT_LOAD_START';
export const PRODUCT_LOAD_FINISH = 'PRODUCT_LOAD_FINISH';
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_LOAD_ERROR = 'PRODUCT_LOAD_ERROR';
export const PRODUCT_LOAD_SUCCESS_ITEM = 'PRODUCT_LOAD_SUCCESS_ITEM';
export const PRODUCT_UPDATE_OBJECT = 'PRODUCT_UPDATE_OBJECT';
export const PRODUCT_ADD_NEW = 'PRODUCT_ADD_NEW';
export const PRODUCT_DELETE_OK = 'PRODUCT_DELETE_OK';
export const PRODUCT_CLEAR_ERROR = 'PRODUCT_CLEAR_ERROR';

