//product reducer
export const PRODUCT_LOAD_START = 'PRODUCT_LOAD_START';
export const PRODUCT_LOAD_FINISH = 'PRODUCT_LOAD_FINISH';
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_LOAD_ERROR = 'PRODUCT_LOAD_ERROR';
export const PRODUCT_LOAD_SUCCESS_ITEM = 'PRODUCT_LOAD_SUCCESS_ITEM';
export const PRODUCT_UPDATE_OBJECT = 'PRODUCT_UPDATE_OBJECT';
export const PRODUCT_ADD_NEW = 'PRODUCT_ADD_NEW';
export const PRODUCT_DELETE_OK = 'PRODUCT_DELETE_OK';
export const PRODUCT_CLEAR_ERROR = 'PRODUCT_CLEAR_ERROR';

//raw reducer
export const RAW_LOAD_START = 'RAW_LOAD_START';
export const RAW_LOAD_FINISH = 'RAW_LOAD_FINISH';
export const RAW_LOAD_SUCCESS = 'RAW_LOAD_SUCCESS';
export const RAW_LOAD_ERROR = 'RAW_LOAD_ERROR';
export const RAW_LOAD_SUCCESS_ITEM = 'RAW_LOAD_SUCCESS_ITEM';
export const RAW_UPDATE_OBJECT = 'RAW_UPDATE_OBJECT';
export const RAW_ADD_NEW = 'RAW_ADD_NEW';
export const RAW_DELETE_OK = 'RAW_DELETE_OK';
export const RAW_CLEAR_ERROR = 'RAW_CLEAR_ERROR';

//formula reducer
export const FORMULA_LOAD_START = 'FORMULA_LOAD_START';
export const FORMULA_LOAD_FINISH = 'FORMULA_LOAD_FINISH';
export const FORMULA_LOAD_SUCCESS = 'FORMULA_LOAD_SUCCESS';
export const FORMULA_DELETE_OK = 'FORMULA__DELETE_OK';
export const FORMULA_ITEM_SUCCESS = 'FORMULA_ITEM_SUCCESS';


//tare reducer
export const TARE_LOAD_START = 'TARE_LOAD_START';
export const TARE_LOAD_FINISH = 'TARE_LOAD_FINISH';
export const TARE_LOAD_SUCCESS = 'TARE_LOAD_SUCCESS';
export const TARE_ITEM_SUCCESS = 'TARE_ITEM_SUCCESS';
export const TARE_DELETE_OK = 'TARE_DELETE_OK';
export const TARE_UPDATE_OBJECT = 'TARE_UPDATE_OBJECT';
export const TARE_SET_ERROR = 'TARE_SET_ERROR';
export const TARE_CLEAR_ERROR = 'TARE_CLEAR_ERROR';


//unit reducer
export const UNIT_LOAD_START = 'UNIT_LOAD_START';
export const UNIT_LOAD_FINISH = 'UNIT_LOAD_FINISH';
export const UNIT_LOAD_SUCCESS = 'UNIT_LOAD_SUCCESS';
export const UNIT_ITEM_SUCCESS = 'UNIT_ITEM_SUCCESS';
export const UNIT_DELETE_OK = 'UNIT_DELETE_OK';
export const UNIT_UPDATE_OBJECT = 'UNIT_UPDATE_OBJECT';
export const UNIT_SET_ERROR = 'UNIT_SET_ERROR';
export const UNIT_CLEAR_ERROR = 'UNIT_CLEAR_ERROR';

//STAFF reducer
export const STAFF_LOAD_START = 'STAFF_LOAD_START';
export const STAFF_LOAD_FINISH = 'STAFF_LOAD_FINISH';
export const STAFF_LOAD_SUCCESS = 'STAFF_LOAD_SUCCESS';
export const STAFF_ITEM_SUCCESS = 'STAFF_ITEM_SUCCESS';
export const STAFF_DELETE_OK = 'STAFF_DELETE_OK';
export const STAFF_UPDATE_OBJECT = 'STAFF_UPDATE_OBJECT';
export const STAFF_SET_ERROR = 'STAFF_SET_ERROR';
export const STAFF_CLEAR_ERROR = 'STAFF_CLEAR_ERROR';


//inform reducer
export const INFO_SHOW_MESSAGE = 'INFO_SHOW_MESSAGE';
export const INFO_HIDE_MESSAGE = 'INFO_HIDE_MESSAGE'
