//product reducer
export const PRODUCT_LOAD_START = 'PRODUCT_LOAD_START'
export const PRODUCT_LOAD_FINISH = 'PRODUCT_LOAD_FINISH'
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS'
export const PRODUCT_LOAD_ERROR = 'PRODUCT_LOAD_ERROR'
export const PRODUCT_LOAD_SUCCESS_ITEM = 'PRODUCT_LOAD_SUCCESS_ITEM'
export const PRODUCT_UPDATE_OBJECT = 'PRODUCT_UPDATE_OBJECT'
export const PRODUCT_ADD_NEW = 'PRODUCT_ADD_NEW'
export const PRODUCT_DELETE_OK = 'PRODUCT_DELETE_OK'
export const PRODUCT_CLEAR_ERROR = 'PRODUCT_CLEAR_ERROR'

//raw reducer
export const RAW_LOAD_START = 'RAW_LOAD_START'
export const RAW_LOAD_FINISH = 'RAW_LOAD_FINISH'
export const RAW_LOAD_SUCCESS = 'RAW_LOAD_SUCCESS'
export const RAW_LOAD_ERROR = 'RAW_LOAD_ERROR'
export const RAW_LOAD_SUCCESS_ITEM = 'RAW_LOAD_SUCCESS_ITEM'
export const RAW_UPDATE_OBJECT = 'RAW_UPDATE_OBJECT'
export const RAW_ADD_NEW = 'RAW_ADD_NEW'
export const RAW_DELETE_OK = 'RAW_DELETE_OK'
export const RAW_CLEAR_ERROR = 'RAW_CLEAR_ERROR'

//materials
export const MATERIAL_LOAD_START = 'MATERIAL_LOAD_START'
export const MATERIAL_LOAD_FINISH = 'MATERIAL_LOAD_FINISH'
export const MATERIAL_LOAD_SUCCESS = 'MATERIAL_LOAD_SUCCESS'

//stock reducer
export const STOCK_LOAD_START = 'STOCK_LOAD_START'
export const STOCK_LOAD_FINISH = 'STOCK_LOAD_FINISH'
export const STOCK_LOAD_SUCCESS = 'STOCK_LOAD_SUCCESS'
export const STOCK_LOAD_ERROR = 'STOCK_LOAD_ERROR'
export const STOCK_LOAD_SUCCESS_ITEM = 'STOCK_LOAD_SUCCESS_ITEM'
export const STOCK_UPDATE_OBJECT = 'STOCK_UPDATE_OBJECT'
export const STOCK_ADD_NEW = 'STOCK_ADD_NEW'
export const STOCK_DELETE_OK = 'STOCK_DELETE_OK'
export const STOCK_CLEAR_ERROR = 'STOCK_CLEAR_ERROR'

//formula reducer
export const FORMULA_LOAD_START = 'FORMULA_LOAD_START'
export const FORMULA_LOAD_FINISH = 'FORMULA_LOAD_FINISH'
export const FORMULA_LOAD_SUCCESS = 'FORMULA_LOAD_SUCCESS'
export const FORMULA_DELETE_OK = 'FORMULA__DELETE_OK'
export const FORMULA_ITEM_SUCCESS = 'FORMULA_ITEM_SUCCESS'
export const FORMULA_UPDATE_OBJECT = 'FORMULA_UPDATE_OBJECT'
export const FORMULA_SET_ERROR = 'FORMULA_SET_ERROR'
export const FORMULA_GET_REFERENCE = 'FORMULA_GET_REFERENCE'


//tare reducer
export const TARE_LOAD_START = 'TARE_LOAD_START'
export const TARE_LOAD_FINISH = 'TARE_LOAD_FINISH'
export const TARE_LOAD_SUCCESS = 'TARE_LOAD_SUCCESS'
export const TARE_ITEM_SUCCESS = 'TARE_ITEM_SUCCESS'
export const TARE_DELETE_OK = 'TARE_DELETE_OK'
export const TARE_UPDATE_OBJECT = 'TARE_UPDATE_OBJECT'
export const TARE_SET_ERROR = 'TARE_SET_ERROR'
export const TARE_CLEAR_ERROR = 'TARE_CLEAR_ERROR'
export const TARE_OK_OPERATION = 'TARE_OK_OPERATION'
export const TARE_START_OPERATION = 'TARE_START_OPERATION'


//team reducer
export const TEAM_LOAD_START = 'TEAM_LOAD_START'
export const TEAM_LOAD_FINISH = 'TEAM_LOAD_FINISH'
export const TEAM_LOAD_SUCCESS = 'TEAM_LOAD_SUCCESS'
export const TEAM_LOAD_ITEM_SUCCESS = 'TEAM_LOAD_ITEM_SUCCESS'
export const TEAM_DELETE_OK = 'TEAM_DELETE_OK'


//unit reducer
export const UNIT_LOAD_START = 'UNIT_LOAD_START'
export const UNIT_LOAD_FINISH = 'UNIT_LOAD_FINISH'
export const UNIT_LOAD_SUCCESS = 'UNIT_LOAD_SUCCESS'
export const UNIT_ITEM_SUCCESS = 'UNIT_ITEM_SUCCESS'
export const UNIT_DELETE_OK = 'UNIT_DELETE_OK'
export const UNIT_UPDATE_OBJECT = 'UNIT_UPDATE_OBJECT'
export const UNIT_SET_ERROR = 'UNIT_SET_ERROR'
export const UNIT_CLEAR_ERROR = 'UNIT_CLEAR_ERROR'

//STAFF reducer
export const STAFF_LOAD_START = 'STAFF_LOAD_START'
export const STAFF_LOAD_FINISH = 'STAFF_LOAD_FINISH'
export const STAFF_LOAD_SUCCESS = 'STAFF_LOAD_SUCCESS'
export const STAFF_ITEM_SUCCESS = 'STAFF_ITEM_SUCCESS'
export const STAFF_DELETE_OK = 'STAFF_DELETE_OK'
export const STAFF_UPDATE_OBJECT = 'STAFF_UPDATE_OBJECT'
export const STAFF_SET_ERROR = 'STAFF_SET_ERROR'
export const STAFF_CLEAR_ERROR = 'STAFF_CLEAR_ERROR'


//inform reducer
export const INFO_SHOW_MESSAGE = 'INFO_SHOW_MESSAGE'
export const INFO_HIDE_MESSAGE = 'INFO_HIDE_MESSAGE'


//factoryLine reducer
export const FACTORY_LINE_LOAD_START = 'FACTORY_LINE_LOAD_START'
export const FACTORY_LINE_LOAD_FINISH = 'FACTORY_LINE_LOAD_FINISH'
export const FACTORY_LINE_LOAD_SUCCESS = 'FACTORY_LINE_LOAD_SUCCESS'
export const FACTORY_LINE_LOAD_ITEM = 'FACTORY_LINE_LOAD_ITEM'
export const FACTORY_LINE_DELETE_OK = 'FACTORY_LINE_DELETE_OK'
export const FACTORY_LINE_SET_ERROR = 'FACTORY_LINE_SET_ERROR'
export const FACTORY_CLEAR_ERROR = 'FACTORY_CLEAR_ERROR'
export const FACTORY_LINE_UPDATE = 'FACTORY_LINE_UPDATE'


//production reducer
export const PROD_LOAD_START = 'PROD_LOAD_START'
export const PROD_LOAD_FINISH = 'PROD_LOAD_FINISH'
export const PROD_LOAD_SUCCESS = 'PROD_LOAD_SUCCESS'
export const PROD_SET_ERROR = 'PROD_SET_ERROR'
export const PROD_CLEAR_ERROR = 'PROD_CLEAR_ERROR'
export const PROD_LOAD_ITEM_SUCCESS = 'PROD_LOAD_ITEM_SUCCESS'
export const PROD_CHANGE_ITEM = 'PROD_CHANGE_ITEM'
export const PROD_TEAM_LOAD_SUCCESS = 'PROD_TEAM_LOAD_SUCCESS'
export const PROD_CALC_LOAD_SUCCESS = 'PROD_CALC_LOAD_SUCCESS'
export const PROD_TARE_LOAD_SUCCESS = 'PROD_TARE_LOAD_SUCCESS'
export const PROD_MATERIAL_LOAD_SUCCESS = 'PROD_MATERIAL_LOAD_SUCCESS'
export const PROD_TEAM_CHANGE = 'PROD_TEAM_CHANGE'
export const PROD_CALC_CHANGE = 'PROD_CALC_CHANGE'
export const PROD_TARE_CHANGE = 'PROD_TARE_CHANGE'
export const PROD_SAVE_OK = 'PROD_SAVE_OK'
export const PROD_ADD_NEW_OK = 'PROD_ADD_NEW_OK'
export const PROD_ORIGIN_CALC_LOAD_SUCCESS = 'PROD_ORIGIN_CALC_LOAD_SUCCESS'
export const PROD_MATERIAL_CHANGE = 'PROD_MATERIAL_CHANGE'

//employee reducer
export const EMPLOYEE_LOAD_START = 'EMPLOYEE_LOAD_START'
export const EMPLOYEE_LOAD_FINISH = 'EMPLOYEE_LOAD_FINISH'
export const EMPLOYEE_LOAD_SUCCESS = 'EMPLOYEE_LOAD_SUCCESS'
export const EMPLOYEE_SET_ERROR = 'EMPLOYEE_SET_ERROR'
export const EMPLOYEE_DELETE_OK = 'EMPLOYEE_DELETE_OK'
export const EMPLOYEE_ITEM_OK = 'EMPLOYEE_ITEM_OK'
export const EMPLOYEE_UPDATE_ITEM = 'EMPLOYEE_UPDATE_ITEM'
export const EMPLOYEE_CLEAR_ERROR = 'EMPLOYEE_CLEAR_ERROR'
export const EMPLOYEE_LOAD_WORKTIME_SUCCESS = 'EMPLOYEE_LOAD_WORKTIME_SUCCESS'
export const EMPLOYEE_LOAD_WITHOUT_LOGINS = 'EMPLOYEE_LOAD_WITHOUT_LOGINS'
export const EMPLOYEE_CHANGE_FIRED = 'EMPLOYEE_CHANGE_FIRED'
export const EMPLOYEE_SET_NOT_FOUND = 'EMPLOYEE_SET_NOT_FOUND'

//department reducer
export const DEPARTMENT_LOAD_START = 'DEPARTMENT_LOAD_START'
export const DEPARTMENT_LOAD_FINISH = 'DEPARTMENT_LOAD_FINISH'
export const DEPARTMENT_LOAD_SUCCESS = 'DEPARTMENT_LOAD_SUCCESS'
export const DEPARTMENT_LOAD_ITEM_SUCCESS = 'DEPARTMENT_LOAD_ITEM_SUCCESS'
export const DEPARTMENT_DELETE_OK = 'DEPARTMENT_DELETE_OK'
export const DEPARTMENT_SET_ERROR = 'DEPARTMENT_SET_ERROR'
export const DEPARTMENT_CLEAR_ERROR = 'DEPARTMENT_CLEAR_ERROR'

//client
export const CLIENT_LOAD_START = 'CLIENT_LOAD_START'
export const CLIENT_LOAD_FINISH = 'CLIENT_LOAD_FINISH'
export const CLIENT_LOAD_SUCCESS = 'CLIENT_LOAD_SUCCESS'
export const CLIENT_LOAD_ITEM_SUCCESS = 'CLIENT_LOAD_ITEM_SUCCESS'
export const CLIENT_DELETE_OK = 'CLIENT_DELETE_OK'
export const CLIENT_SET_ERROR = 'CLIENT_SET_ERROR'
export const CLIENT_CLEAR_ERROR = 'CLIENT_CLEAR_ERROR'
export const CLIENT_LOAD_CONTRACT_SUCCESS = 'CLIENT_LOAD_CONTRACT_SUCCESS'
export const CLIENT_SEARCH_SUCCESS = 'CLIENT_SEARCH_SUCCESS'
export const CONTRACT_CHANGE_ITEM = 'CONTRACT_CHANGE_ITEM'

//contract
export const CONTRACT_LOAD_START = 'CONTRACT_LOAD_START'
export const CONTRACT_LOAD_FINISH = 'CONTRACT_LOAD_FINISH'
export const CONTRACT_LOAD_SUCCESS = 'CONTRACT_LOAD_SUCCESS'
export const CONTRACT_LOAD_ITEM_SUCCESS = 'CONTRACT_LOAD_ITEM_SUCCESS'
export const CONTRACT_DELETE_OK = 'CONTRACT_DELETE_OK'
export const CONTRACT_SET_ERROR = 'CONTRACT_SET_ERROR'
export const CONTRACT_CLEAR_ERROR = 'CONTRACT_CLEAR_ERROR'
export const CONTRACT_LOAD_ACTIVE_CONTRACTS = 'CONTRACT_LOAD_ACTIVE_CONTRACTS'
export const CONTRACT_SHOW_OWN_CONTRACT_STATE =  'CONTRACT_SHOW_OWN_CONTRACT_STATE'
export const CONTRACT_SET_NOT_FOUND = 'CONTRACT_SET_NOT_FOUND'

//cost
export const COST_LOAD_START = 'COST_LOAD_START'
export const COST_LOAD_FINISH = 'COST_LOAD_FINISH'
export const COST_LOAD_SUCCESS = 'COST_LOAD_SUCCESS'
export const COST_LOAD_FLAT_SUCCESS = 'COST_LOAD_FLAT_SUCCESS'
export const COST_LOAD_ITEM_SUCCESS = 'COST_LOAD_ITEM_SUCCESS'
export const COST_DELETE_OK = 'COST_DELETE_OK'
export const COST_LOAD_PARENT_ITEMS = 'COST_LOAD_PARENT_ITEMS'
export const COST_CHANGE_ITEM = 'COST_CHANGE_ITEM'
export const COST_CLEAR_ERROR = 'COST_CLEAR_ERROR'
export const COST_SAVE_OK = 'COST_SAVE_OK'
export const COST_SET_ERROR = 'COST_SET_ERROR'

// store
export const STORE_LOAD_START = 'STORE_LOAD_START'
export const STORE_LOAD_FINISH = 'STORE_LOAD_FINISH'
export const STORE_LOAD_RAW_SUCCESS = 'STORE_LOAD_RAW_SUCCESS'
export const STORE_LOAD_PRODUCT_SUCCESS = 'STORE_LOAD_PRODUCT_SUCCESS'
export const STORE_LOAD_STOCK_SUCCESS = 'STORE_LOAD_STOCK_SUCCESS'
export const STORE_SET_DATE_PRODUCT_STORE = 'STORE_SET_DATE_PRODUCT_STORE'
export const STORE_SET_DATE_RAW_STORE = 'STORE_SET_DATE_RAW_STORE'
export const STORE_SET_DATE_STOCK_STORE = 'STORE_SET_DATE_STOCK_STORE'
export const STORE_SET_ERROR = 'STORE_SET_ERROR'
export const STORE_CLEAR_ERROR = 'STORE_CLEAR_ERROR'
export const STORE_JOURNAL_SUCCESS = 'STORE_JOURNAL_SUCCESS'
export const STORE_JOURNAL_MATERIAL_SUCCESS = 'STORE_JOURNAL_MATERIAL_SUCCESS'
export const STORE_JOURNAL_ITEM_SUCCESS = 'STORE_JOURNAL_ITEM_SUCCESS'
export const STORE_CHANGE_ITEM = 'STORE_CHANGE_ITEM'
export const STORE_UPDATE_ITEM = 'STORE_UPDATE_ITEM'
export const STORE_NEW_MOVEMENT = 'STORE_NEW_MOVEMENT'
export const STORE_NEW_MOVEMENT_ITEM = 'STORE_NEW_MOVEMENT_ITEM'
export const STORE_ITEM_MOVEMENT_CHANGE = 'STORE_ITEM_MOVEMENT_CHANGE'
export const STORE_ITEM_MOVEMENT_DELETE = 'STORE_ITEM_MOVEMENT_DELETE'
export const STORE_RESERVE_LOAD_SUCCESS = 'STORE_RESERVE_LOAD_SUCCESS'
export const STORE_RESERVE_ITEM_LOAD_SUCCESS = 'STORE_RESERVE_ITEM_LOAD_SUCCESS'
export const STORE_RESERVE_NEW_ITEM = 'STORE_RESERVE_NEW_ITEM'
export const STORE_RESERVE_LOAD_ITEM_SUCCESS = 'STORE_RESERVE_LOAD_ITEM_SUCCESS'
export const STORE_RESERVE_CHANGE_ITEM = 'STORE_RESERVE_CHANGE_ITEM'
export const STORE_RETURNS_LOAD_ITEM_SUCCESS = 'STORE_RETURNS_LOAD_ITEM_SUCCESS'


export const EXPENSE_LOAD_START = 'EXPENSE_LOAD_START'
export const EXPENSE_LOAD_FINISH = 'EXPENSE_LOAD_FINISH'
export const EXPENSE_LOAD_SUCCESS = 'EXPENSE_LOAD_SUCCESS'
export const EXPENSE_LOAD_ITEM_SUCCESS = 'EXPENSE_LOAD_ITEM_SUCCESS'
export const EXPENSE_DELETE_OK = 'EXPENSE_DELETE_OK'
export const EXPENSE_SET_START_DATE = 'EXPENSE_SET_START_DATE'
export const EXPENSE_SET_END_DATE = 'EXPENSE_SET_END_DATE'
export const EXPENSE_SET_COST_VALUE = 'EXPENSE_SET_COST_VALUE'
export const EXPENSE_LOAD_SUCCESS_ITEM = 'EXPENSE_LOAD_SUCCESS_ITEM'
export const EXPENSE_CHANGE_ITEM = 'EXPENSE_CHANGE_ITEM'

//users
export const USER_LOAD_START = 'USER_LOAD_START'
export const USER_LOAD_FINISH = 'USER_LOAD_FINISH'
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS'
export const USER_LOAD_ITEM_SUCCESS = 'USER_LOAD_ITEM_SUCCESS'
export const USER_CHANGE_ITEM = 'USER_CHANGE_ITEM'
export const USER_GROUP_LOAD_SUCCESS = 'USER_GROUP_LOAD_SUCCESS'
export const USER_SET_ERROR = 'USER_SET_ERROR'
export const USER_PROFILE_OK = 'USER_PROFILE_OK'
export const USER_SET_NOFOUND_USER = 'USER_SET_NOFOUND_USER'

//works
export const WORK_LOAD_START = 'WORK_LOAD_START'
export const WORK_LOAD_FINISH = 'WORK_LOAD_FINISH'
export const WORK_LOAD_SUCCESS = 'WORK_LOAD_SUCCESS'
export const WORK_LOAD_ITEM_SUCCESS = 'WORK_LOAD_ITEM_SUCCESS'
export const WORK_DELETE_OK = 'WORK_DELETE_OK'


//payment method
export const PAY_METHOD_LOAD_START = 'PAY_METHOD_LOAD_START'
export const PAY_METHOD_LOAD_FINISH = 'PAY_METHOD_LOAD_FINISH'
export const PAY_METHOD_SUCCESS = 'PAY_METHOD_SUCCESS'
export const PAY_METHOD_SUCCESS_ITEM = 'PAY_METHOD_SUCCESS_ITEM'
export const PAY_METHOD_CHANGE_ITEM = 'PAY_METHOD_CHANGE_ITEM'
export const PAY_METHOD_DELETE_OK = 'PAY_METHOD_DELETE_OK'

//payments
export const PAYMENT_LOAD_START = 'PAYMENT_LOAD_START'
export const PAYMENT_LOAD_FINISH = 'PAYMENT_LOAD_FINISH'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_SUCCESS_ITEM = 'PAYMENT_SUCCESS_ITEM'
export const PAYMENT_CHANGE_ITEM = 'PAYMENT_CHANGE_ITEM'
export const PAYMENT_DELETE_OK = 'PAYMENT_DELETE_OK'

//requisites
export const ORG_LOAD_START = 'ORG_LOAD_START'
export const ORG_LOAD_FINISH = 'ORG_LOAD_FINISH'
export const ORG_LOAD_SUCCESS = 'ORG_LOAD_SUCCESS'
export const ORG_CHANGE_ITEM = 'ORG_CHANGE_ITEM'


//setup
export const SETUP_LOAD = 'SETUP_LOAD'
export const SETUP_FETCH_NDS_SUCCESS = 'SETUP_FETCH_NDS_SUCCESS'
export const SETUP_FETCH_RESERVE_INTERVAL = 'SETUP_FETCH_RESERVE_INTERVAL'


//price list
export const PRICE_LOAD_START = 'PRICE_LOAD_START'
export const PRICE_LOAD_FINISH = 'PRICE_LOAD_FINISH'
export const PRICE_LOAD_SUCCESS = 'PRICE_LOAD_SUCCESS'
export const PRICE_DELETE_OK = 'PRICE_DELETE_OK'
export const PRICE_CHANGE_ITEM = 'PRICE_CHANGE_ITEM'
export const PRICE_LOAD_ITEM_SUCCESS = 'PRICE_LOAD_ITEM_SUCCESS'
export const PRICE_LOAD_HISTORY_SUCCESS = 'PRICE_LOAD_HISTORY_SUCCESS'
export const PRICE_LOAD_BY_EMPLOYEE_SUCCESS = 'PRICE_LOAD_BY_EMPLOYEE_SUCCESS'

//notifications
export const NOTICE_LOAD_OK = 'NOTICE_LOAD_OK'


//return products
export const RETURNS_LOAD_START = 'RETURNS_LOAD_START'
export const RETURNS_LOAD_FINISH = 'RETURNS_LOAD_FINISH'
export const RETURNS_LOAD_OK = 'RETURNS_LOAD_OK'
export const RETURNS_LOAD_ITEM = 'RETURNS_LOAD_ITEM'
