version: '3'

volumes:
  pgsql:
  static_files:
  migrations:

services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - POSTGRES_PASSWORD=lighthouse
    - POSTGRES_USER=lighthouse
    - POSTGRES_DB=lighthouse
    - POSTGRES_HOST=postgres
    - DJANGO_SETTINGS_MODULE=api.production
    - HTTP_FRONTEND_URL=http://lighthouse.kz
    - TIME_ZONE=Asia/Almaty
    volumes:
      - ./static_files:/static_files
      - ./migrations:/lighthouse/lighthouse/migrations
    links:
      - postgres
    command: ./docker-entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lighthouse
      POSTGRES_USER: lighthouse
      POSTGRES_DB: lighthouse

  djangoweb:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - python
      - postgres
    volumes:
      - ./static_files:/static_files
    ports:
      - 8000:80

  cache:
    image: memcached
    ports:
      - 12211:12211
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      - djangoweb
    environment:
    - REACT_APP_HTTP_API_URL=http://lighthouse.kz:8000
    ports:
      - 80:3000
    stdin_open: true
    tty: true