name: CD to VPS

on:
  push:
    
    branches:
      - 'releases/**'
      - '!releases/**-alpha'

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
     
  deploy:

    runs-on: [ubuntu-18.04]

    steps:
    - name: deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secret.SERVER_KEY }}
        script: |
          cd lighthouse
          # docker-compose down
          git pull origin
          # sudo docker-compose build
          # docker-compose up --detach
